[package]
name = "gb_emu"
version = "0.1.0"
authors = ["Roberto Nazareth"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
